<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-04-30T16:07:17Z" name="Suite" finished-at="2020-04-30T16:08:06Z" duration-ms="48979">
    <groups>
    </groups>
    <test started-at="2020-04-30T16:07:17Z" name="Test" finished-at="2020-04-30T16:08:06Z" duration-ms="48979">
      <class name="com.fremwworkdev.Testcase.Login">
        <test-method is-config="true" signature="setup(org.testng.ITestContext)[pri:0, instance:com.fremwworkdev.Testcase.Login@6b4a4e18]" started-at="2020-04-30T16:07:11Z" name="setup" finished-at="2020-04-30T16:07:17Z" duration-ms="5940" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5467eea4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_in()[pri:1, instance:com.fremwworkdev.Testcase.Login@6b4a4e18]" started-at="2020-04-30T16:07:17Z" name="Login_in" finished-at="2020-04-30T16:07:49Z" duration-ms="31828" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_in -->
        <test-method is-config="true" signature="terminate()[pri:0, instance:com.fremwworkdev.Testcase.Login@6b4a4e18]" started-at="2020-04-30T16:08:07Z" name="terminate" finished-at="2020-04-30T16:08:13Z" duration-ms="5791" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminate -->
      </class> <!-- com.fremwworkdev.Testcase.Login -->
      <class name="com.fremwworkdev.Testcase.Add_customer">
        <test-method signature="call_Add_customer()[pri:1, instance:com.fremwworkdev.Testcase.Add_customer@27c86f2d]" started-at="2020-04-30T16:07:50Z" name="call_Add_customer" finished-at="2020-04-30T16:08:05Z" duration-ms="15443" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Email is already registered]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Email is already registered
at junit.framework.Assert.fail(Assert.java:47)
at com.fameworkdev.pageobject.page_objectclass_customerfunctions.add_customer(page_objectclass_customerfunctions.java:98)
at com.fremwworkdev.Testcase.Add_customer.call_Add_customer(Add_customer.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- call_Add_customer -->
      </class> <!-- com.fremwworkdev.Testcase.Add_customer -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
